language: node_js
node_js:
  - "10"
before_install:
  - sudo pip install awscli
  - npm install -g @angular/cli
script:
  - npm run lint || travis_terminate 1
  - npm run build || travis_terminate 1
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: "www.playyourdamnturn.com"
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  cache_control: "max-age=31536000"
after_deploy:
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/index.html --bucket www.playyourdamnturn.com --key index.html --metadata-directive REPLACE --cache-control "max-age=0" --content-type "text/html" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/ngsw.json --bucket www.playyourdamnturn.com --key ngsw.json --metadata-directive REPLACE --cache-control "max-age=0" --content-type "application/json" --acl public-read
branches:
  only:
  - master