language: node_js
node_js:
  - "12"
before_install:
  - sudo pip install awscli
script:
  - npm run build || travis_terminate 1
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: "www.playyourdamnturn.com"
  skip_cleanup: true
  local_dir: dist/web/browser
  acl: public_read
  cache_control: "max-age=31536000"
after_deploy:
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/index.html --bucket www.playyourdamnturn.com --key index.html --metadata-directive REPLACE --cache-control "max-age=0" --content-type "text/html" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/index.original.html --bucket www.playyourdamnturn.com --key index.original.html --metadata-directive REPLACE --cache-control "max-age=0" --content-type "text/html" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/manifest.webmanifest --bucket www.playyourdamnturn.com --key manifest.webmanifest --metadata-directive REPLACE --cache-control "max-age=0" --content-type "application/manifest+json" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/ngsw.json --bucket www.playyourdamnturn.com --key ngsw.json --metadata-directive REPLACE --cache-control "max-age=0" --content-type "application/json" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/ngsw-worker.js --bucket www.playyourdamnturn.com --key ngsw-worker.js --metadata-directive REPLACE --cache-control "max-age=0" --content-type "application/javascript" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/pydt-service-worker.js --bucket www.playyourdamnturn.com --key pydt-service-worker.js --metadata-directive REPLACE --cache-control "max-age=0" --content-type "application/javascript" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/robots.txt --bucket www.playyourdamnturn.com --key robots.txt --metadata-directive REPLACE --cache-control "max-age=0" --content-type "text/plain" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/safety-worker.js --bucket www.playyourdamnturn.com --key safety-worker.js --metadata-directive REPLACE --cache-control "max-age=0" --content-type "application/javascript" --acl public-read
  - aws s3api copy-object --copy-source www.playyourdamnturn.com/worker-basic.min.js --bucket www.playyourdamnturn.com --key worker-basic.min.js --metadata-directive REPLACE --cache-control "max-age=0" --content-type "application/javascript" --acl public-read
branches:
  only:
  - master